### ISSUE TITLE
OKCO#6 - Eliminar la action de SonarLint

### ISSUE THREAD

**Issue by Indenaiten** [oinkeep/oinkeep#10]
Se necesita eliminar la configuración de la action de SonarLint realizada en la issue #6 por que no esta funcionando correctamente y no nos permite realizar las PR y avanzar con el desarrollo del proyecto.

**Comment by Patrifgonz** [comment]
Se ha revertido el commit realizado en la tarea OKCO#4 para eliminar la action de Sonar
