### ISSUE TITLE
OKCO#4 - Establecer Sonar en Git Action

### ISSUE THREAD

**Issue by Indenaiten** [oinkeep/oinkeep#6]
## Establecer el analizador de Sonar en el repositorio

Se requiere establecer una Git Action en el proyecto para evitar incorporar código con errores/warnings de SonarLint.

**Comment by Patrifgonz** [comment]
Configurar GitAction para analizar el código con Sonar:

1. Configurar SonarQube. Tener un servidor de SonarQube en funcionamiento y acceso a la URL y token de análisis.
      Acceder al siguiente link https://sonarcloud.io/ con la cuenta de GitHub. Vincular el repositorio de Github, en este caso Oinkeep. 
      Desde My organizations > Create > Seguir los pasos vinculando la organizacion de Github
2. A continuacion, desde sonarCloud, vamos al proyecto recien creado, nos aparecerá algo tipo, Analizar codigo, accedemos y nos irá guiando.
3. Primero nos redirige a la pagina de github a configurar un nuevo secreto
4. A continucion nos indicará los cambios necesarios a hacer, añadir unas líneas de configuracion en el pom.xml y añadir el fichero de la git action sonarcloud.yml
