### ISSUE TITLE
OKCO#5 - Crear un Usuario

### ISSUE THREAD

**Issue by Indenaiten** [oinkeep/oinkeep#8]
## Descripción

Se requiere añadir la funcionalidad de creación de usuarios.

## Detalles

Un usuario deberá de tener los siguientes campos:

- **id**: El usuario tendrá un identificativo único.
- **Imágen de perfil**: Una imagen con el que se identifique un usuario.
- **Username:** El nombre del usuario que se va a utilizar en la aplicación, el username debe ser único.
- **Nombre y Apellidos**: El nombre y apellidos del usuario real.

## Requerimientos

Creación de la entidad de Usuario y el servicio que nos permita crear un usuario.

**Comment by Indenaiten** [comment]
## Realizado

- Se han añadido las siguientes clases genéricas al módulo "util": DTO, ValueObject y Entity.

- Se ha creado la entidad de usuario y sus correspondientes ValueObjects (UserId, Username).

- Se ha creado un DTO con la información para crear un nuevo usuario.

- Se ha creado el servicio de usuarios con el método de creación de un nuevo usuario.

- Se ha creado la interfaz del repositorio de usuarios con el método para guardar un nuevo usuario.

- Se han creado los tests para comprobar que cuando se crea un nuevo usuario con los datos correctos mediante el servicio de usuarios se cree correctamente.

- Se ha añadido la dependencia de "mockito-junit-jupiter" con la versión "5.6.0".

- Se han creado los tests para comprobar que cuando se crea un nuevo usuario con datos incorrectos mediante el servicio de usuarios salta el correspondiente error.

- Se ha eliminado todo lo que tiene que ver con el ejemplo de prueba que se había realizado (TestService).

- Se ha renombrado el módulo "plugin" por "data".

## Por hacer

- Falta crear los ValueObjects para el nombre y los apellidos (Name, LastName).

- Faltan crear los tests para para los ValueObjects que se han creado (UserId, Username) y los que faltan por crear (Name, LastName).

- Faltan crear los test para el entidad User que se ha creado.

- Falta revisar los tests creados para comprobar el funcionamiento de la creación de usuarios y crear los que hagan falta.

**Comment by Patrifgonz** [comment]
## Realizado

- Creados los ValueObjects para el nombre y los apellidos (Name, LastName).

- Creados los tests para para los ValueObjects que se han creado (UserId, Username) y los que faltan por crear (Name, LastName).

- Creados los test para el entidad User que se ha creado.

## Por hacer

- Falta revisar los tests creados para comprobar el funcionamiento de la creación de usuarios y crear los que hagan falta.

- Creacion de excepciones para los errores en el repositorio y la validacion de datos

- Comprobar que el username no existe cuando a la hora de crear un usuario

**Comment by Indenaiten** [comment]
## Tarea finalizada

- Se ha eliminado todo lo que tiene que ver con el ejemplo de prueba que se había realizado (TestService).

- Se ha renombrado el módulo "plugin" por "data".

- Se ha añadido la dependencia de "mockito-junit-jupiter" con la versión "5.6.0".

- Se han añadido las siguientes clases genéricas al módulo "util": DTO, ValueObject y Entity.

- Se han establecido los mensajes de la aplicación en clases enum.

- Se han creado los ValueObject UserId, Username, Name y LastName.

- Se ha creado la entidad de usuario.

- Se ha creado un DTO con la información para crear un nuevo usuario.

- Se ha creado el servicio de usuarios con el método de creación de un nuevo usuario.

- Se ha creado la interfaz del repositorio de usuarios con el método para guardar un nuevo usuario y para comprobar si existe un usuario con un determinado username.

- Se ha actualizado el fichero COMMIT_CONVENTION.md para añadir un nuevo tipo de commit (change).

- Se han creado los tests necesarios para comprobar que los ValueObjects que se han creado (UserId, Username, Name y LastName) funcionan correctamente.

- Se han creado los tests necesarios para comprobar que la Entidad de usuario funciona correctamente.

- Se han creado los tests necesarios para comprobar que la nueva funcionalidad de creación de usuario implementada en el servicio de usuarios funciona correctamente.
